from __future__ import annotations
"""
Parameter loading: safe dict navigation, tuned Kalman parameter cache loading,
and regime-specific parameter selection.

Extracted from signals.py (Story 6.3). Contains _safe_get_nested for safe dict
traversal, _load_tuned_kalman_params for loading BMA parameter caches, and
_select_regime_params for regime-first parameter routing.
"""
import json
import os
import sys
from typing import Dict, Optional

import numpy as np

# -- path setup so "from tuning..." works when run standalone ----------
_SRC_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if _SRC_DIR not in sys.path:
    sys.path.insert(0, _SRC_DIR)


def _safe_get_nested(d: any, keys: list, default: any = None) -> any:
    """
    Safely get a nested value from a dict, returning default if any key is missing
    or if any intermediate value is not a dict.
    
    Args:
        d: The dict (or None) to get from
        keys: List of keys to traverse
        default: Default value if path doesn't exist
        
    Returns:
        The value at the path, or default if not found
    """
    if d is None or not isinstance(d, dict):
        return default
    
    current = d
    for key in keys:
        if not isinstance(current, dict):
            return default
        current = current.get(key)
        if current is None:
            return default
    
    return current


# =============================================================================
# PER-ASSET CACHE INTEGRATION
# =============================================================================
# Try to use the per-asset cache module for better git-friendliness
# Falls back to legacy single-file cache if not available
# =============================================================================
try:
    from tuning.kalman_cache import load_tuned_params as _load_per_asset_cache
    PER_ASSET_CACHE_AVAILABLE = True
except ImportError:
    # Try adding src directory to path if running from project root
    import sys
    # Get src/ directory (parent of decision/)
    _src_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if _src_dir not in sys.path:
        sys.path.insert(0, _src_dir)
    try:
        from tuning.kalman_cache import load_tuned_params as _load_per_asset_cache
        PER_ASSET_CACHE_AVAILABLE = True
    except ImportError:
        PER_ASSET_CACHE_AVAILABLE = False


def _load_tuned_kalman_params(asset_symbol: str, cache_path: str = "src/data/tune") -> Optional[Dict]:
    """
    Load pre-tuned Kalman parameters from cache generated by tune.py.

    Supports the Bayesian Model Averaging (BMA) structure from tune.py:
    
    {
        "global": {
            "model_posterior": { m: p(m) },
            "models": { m: {q, phi, nu, c, ...} },
            ...backward-compatible fields...
        },
        "regime": {
            "r": {
                "model_posterior": { m: p(m|r) },
                "models": { m: {q, phi, nu, c, ...} },
                "regime_meta": {
                    "fallback": bool,
                    "borrowed_from_global": bool,
                    ...
                }
            }
        }
    }
    
    CONTRACT WITH tune.py:
    - Cache structure is ALWAYS: {"global": {...}, "regime": {...}}
    - Every regime block contains model_posterior and models
    - Fallback regimes have borrowed_from_global=True but still contain valid models
    - This function does NOT perform fallback logic - tune guarantees non-empty outputs
    - NO backward compatibility with old flat schema - new BMA architecture only
    
    Args:
        asset_symbol: Asset symbol (e.g., "PLNJPY=X", "SPY")
        cache_path: Path to the tuned parameters cache file (legacy fallback)
        
    Returns:
        Dictionary with BMA structure if found, None otherwise. Contains:
        - 'global': {model_posterior, models}
        - 'regime': {r: {model_posterior, models, regime_meta}}
        - 'has_bma': True (always for valid entries)
    """
    raw_data = None
    
    # Try per-asset cache first (preferred)
    if PER_ASSET_CACHE_AVAILABLE:
        raw_data = _load_per_asset_cache(asset_symbol)
    
    # Fallback to legacy single-file cache
    if raw_data is None:
        try:
            if not os.path.exists(cache_path):
                return None
            with open(cache_path, 'r') as f:
                cache = json.load(f)
            if asset_symbol not in cache:
                return None
            raw_data = cache[asset_symbol]
        except Exception:
            return None
    
    if raw_data is None:
        return None
        
    # ====================================================================
    # NEW BMA ARCHITECTURE ONLY - NO BACKWARD COMPATIBILITY
    # ====================================================================
    # tune.py outputs:
    #   {
    #     "global": { "model_posterior": {...}, "models": {...} },
    #     "regime": { "0": {...}, "1": {...}, ... },
    #     "meta": {...}
    #   }
    #
    # Old flat schema is NOT supported. If cache doesn't have 'global' key,
    # it's from old architecture and must be regenerated.
    # ====================================================================
    
    if 'global' not in raw_data:
        # Old flat schema - not supported - ALWAYS warn user
        import sys
        print(f"\n⚠️  CACHE FORMAT ERROR for {asset_symbol}:", file=sys.stderr)
        print(f"   Cache entry exists but uses OLD flat schema (missing 'global' key)", file=sys.stderr)
        print(f"   Top-level keys in cache: {list(raw_data.keys())[:10]}", file=sys.stderr)
        print(f"   → Fix: Run 'make tune ARGS=\"--assets {asset_symbol}\"' to regenerate\n", file=sys.stderr)
        return None

    global_data = raw_data['global']
    regime_data = raw_data.get('regime', {})
    
    # Guard against malformed cache where global_data is None
    if not isinstance(global_data, dict):
        import sys
        print(f"\n⚠️  CACHE STRUCTURE ERROR for {asset_symbol}:", file=sys.stderr)
        print(f"   'global' key exists but contains {type(global_data).__name__} instead of dict", file=sys.stderr)
        print(f"   → Fix: Run 'make tune ARGS=\"--assets {asset_symbol}\"' to regenerate\n", file=sys.stderr)
        return None

    # Validate BMA structure
    model_posterior = global_data.get('model_posterior', {})
    models = global_data.get('models', {})

    if not models:
        # Invalid BMA structure - no models - ALWAYS warn user
        import sys
        print(f"\n⚠️  CACHE STRUCTURE ERROR for {asset_symbol}:", file=sys.stderr)
        print(f"   Cache entry has 'global' key but no models inside", file=sys.stderr)
        print(f"   → Fix: Run 'make tune ARGS=\"--assets {asset_symbol}\"' to regenerate\n", file=sys.stderr)
        return None

    # Helper to check if model is Student-t (phi_student_t_nu_* naming)
    # Also handles unified variants (phi_student_t_unified_nu_*)
    # Also handles legacy momentum-augmented variants (phi_student_t_nu_*_momentum) for cached compatibility
    def _is_student_t(model_name: str) -> bool:
        # Strip momentum suffix if present (legacy cache compatibility)
        base_name = model_name[:-9] if model_name.endswith('_momentum') else model_name
        return base_name.startswith('phi_student_t_nu_') or base_name.startswith('phi_student_t_unified_nu_')
    
    # Helper to check if model has internal momentum augmentation active
    # (either via legacy _momentum suffix or via internal momentum_augmented flag)
    def _is_momentum_augmented(model_name: str) -> bool:
        if model_name.endswith('_momentum'):
            return True  # Legacy cache compatibility
        m_params = models.get(model_name, {})
        return isinstance(m_params, dict) and m_params.get('momentum_augmented', False)
    
    # Helper to get base model name (strip _momentum suffix for legacy cache)
    def _get_base_model_name(model_name: str) -> str:
        return model_name[:-9] if model_name.endswith('_momentum') else model_name
    
    # Helper to check if a model fit successfully
    def _is_valid_model(model_name: str) -> bool:
        m_params = models.get(model_name, {})
        return isinstance(m_params, dict) and m_params.get('fit_success', False)

    # Extract representative params from highest-posterior model for Kalman filter
    # (The BMA path uses full model averaging, but Kalman filter needs single params)
    # IMPORTANT: Only consider models with fit_success=True
    if model_posterior:
        # Filter to only successfully fitted models
        valid_models = {m: p for m, p in model_posterior.items() if _is_valid_model(m)}
        if valid_models:
            best_model = max(valid_models.keys(), key=lambda m: valid_models.get(m, 0))
        else:
            # Fallback if no valid models in posterior (shouldn't happen)
            best_model = None
    else:
        # Fallback order: any Student-t > phi_gaussian > gaussian
        # First check for new naming (phi_student_t_nu_*) - only if fit succeeded
        student_t_models = [m for m in models if _is_student_t(m) and _is_valid_model(m)]
        if student_t_models:
            best_model = student_t_models[0]  # Pick first available Student-t
        elif 'kalman_phi_gaussian' in models and _is_valid_model('kalman_phi_gaussian'):
            best_model = 'kalman_phi_gaussian'
        elif 'kalman_gaussian' in models and _is_valid_model('kalman_gaussian'):
            best_model = 'kalman_gaussian'
        else:
            # Pick any valid model
            valid_any = [m for m in models if _is_valid_model(m)]
            best_model = valid_any[0] if valid_any else None

    if not best_model or best_model not in models:
        return None
    
    best_params = models[best_model]
    
    # Ensure best_params is a valid dict (guard against malformed cache data)
    if not isinstance(best_params, dict):
        return None

    # Extract params from best model
    q_val = best_params.get('q')
    c_val = best_params.get('c', 1.0)
    phi_val = best_params.get('phi')
    nu_val = best_params.get('nu')

    # Derive noise_model from best model name
    # Normalize to standard categories for downstream processing
    # Handle legacy _momentum suffix for cached compatibility
    base_model_for_noise = _get_base_model_name(best_model)
    
    # RV-Q models: pass through as-is so dispatch can detect rv_q_ prefix
    if base_model_for_noise.startswith('rv_q_'):
        noise_model = base_model_for_noise
    elif _is_student_t(best_model):
        noise_model = base_model_for_noise  # Use base model name (e.g., phi_student_t_nu_6)
    elif 'phi' in base_model_for_noise:
        noise_model = 'kalman_phi_gaussian'
    else:
        noise_model = 'gaussian'
    
    # Track if momentum augmentation is active (internal flag or legacy suffix)
    is_momentum_model = _is_momentum_augmented(best_model)
    
    # Full model name for tracking/display
    full_model_name = best_model

    # Validate required params
    if q_val is None or not np.isfinite(q_val) or q_val <= 0:
        return None
    if c_val is None or not np.isfinite(c_val) or c_val <= 0:
        return None

    result = {
        # Full BMA structure from tune.py
        'global': global_data,
        'regime': regime_data,
        'has_bma': True,

        # Representative params from best model (for Kalman filter compatibility)
        'q': float(q_val),
        'c': float(c_val),
        'phi': float(phi_val) if phi_val is not None and np.isfinite(phi_val) else None,
        'nu': float(nu_val) if nu_val is not None and np.isfinite(nu_val) else None,
        'noise_model': noise_model,
        'best_model': best_model,
        'is_momentum_model': is_momentum_model,

        # RV-Q specific parameters (q_base, gamma for proactive vol-adaptive noise)
        'q_base': best_params.get('q_base'),
        'gamma': best_params.get('gamma'),
        'rv_q_model': best_params.get('rv_q_model', False),

        # Diagnostics from best model (for display compatibility)
        'bic': best_params.get('bic'),
        'aic': best_params.get('aic'),
        'hyvarinen_score': best_params.get('hyvarinen_score'),
        'combined_score': best_params.get('combined_score'),
        'log_likelihood': best_params.get('log_likelihood'),
        'pit_ks_pvalue': best_params.get('pit_ks_pvalue'),
        'ks_statistic': best_params.get('ks_statistic'),

        # Isotonic Recalibration Transport Map
        # This is the CORE calibration layer - applied BEFORE regimes see PIT
        'recalibration': global_data.get('recalibration'),
        'recalibration_applied': global_data.get('recalibration_applied', False),
        'pit_ks_pvalue_calibrated': global_data.get('pit_ks_pvalue_calibrated'),
        'calibration_diagnostics': global_data.get('calibration_diagnostics'),
        'failure_category': global_data.get('failure_category'),

        # Model comparison: build from all models (includes Hyvärinen scores)
        'model_comparison': {
            m: {
                'bic': m_params.get('bic'),
                'aic': m_params.get('aic'),
                'hyvarinen_score': m_params.get('hyvarinen_score'),
                'combined_score': m_params.get('combined_score'),
                'll': m_params.get('log_likelihood'),
                'n_params': m_params.get('n_params'),
            }
            for m, m_params in models.items()
            if isinstance(m_params, dict) and m_params.get('fit_success', False)
        },

        # Model selection metadata from tune.py
        'model_selection_method': raw_data.get('meta', {}).get('model_selection_method', 'combined'),
        'bic_weight': raw_data.get('meta', {}).get('bic_weight', 0.5),
        'entropy_lambda': raw_data.get('meta', {}).get('entropy_lambda', 0.05),

        # Global-level aggregates (from global block or computed)
        'hyvarinen_max': global_data.get('hyvarinen_max'),
        'combined_score_min': global_data.get('combined_score_min'),
        'bic_min': global_data.get('bic_min'),

        # Calibrated Trust Authority
        # ARCHITECTURAL LAW: Trust = Calibration Authority − Bounded Regime Penalty
        # This is the SINGLE AUTHORITY for trust decisions
        'calibrated_trust': global_data.get('calibrated_trust'),
        'effective_trust': global_data.get('effective_trust'),
        'calibration_trust': global_data.get('calibration_trust'),
        'regime_penalty': global_data.get('regime_penalty'),

        # Calibration status and escalation tracking
        'calibration_warning': global_data.get('calibration_warning', False),
        'nu_refinement': global_data.get('nu_refinement', {}),

        # =====================================================================
        # ENHANCED STUDENT-T MODEL PARAMETERS (February 2026)
        # =====================================================================
        # Vol-of-Vol enhancement
        'vov_enhanced': best_params.get('vov_enhanced', False) if isinstance(best_params, dict) else False,
        'gamma_vov': best_params.get('gamma_vov') if isinstance(best_params, dict) else None,
        
        # Two-Piece asymmetric tails
        'two_piece': best_params.get('two_piece', False) if isinstance(best_params, dict) else False,
        'nu_left': best_params.get('nu_left') if isinstance(best_params, dict) else None,
        'nu_right': best_params.get('nu_right') if isinstance(best_params, dict) else None,
        
        # Two-Component Mixture
        'mixture_model': best_params.get('mixture_model', False) if isinstance(best_params, dict) else False,
        'nu_calm': best_params.get('nu_calm') if isinstance(best_params, dict) else None,
        'nu_stress': best_params.get('nu_stress') if isinstance(best_params, dict) else None,
        'w_base': best_params.get('w_base') if isinstance(best_params, dict) else None,

        # GH distribution fallback
        'gh_attempted': global_data.get('gh_attempted', False),
        'gh_selected': global_data.get('gh_selected', False),
        'gh_model': global_data.get('gh_model'),

        # TVVM (Time-Varying Volatility Multiplier)
        'tvvm_attempted': global_data.get('tvvm_attempted', False),
        'tvvm_selected': global_data.get('tvvm_selected', False),

        # Elite Tuning diagnostics (v2.0 - February 2026)
        # Stability-aware model selection with fragility penalties
        'elite_tuning_enabled': (raw_data.get('meta') or {}).get('elite_tuning_enabled', False),
        'elite_tuning_preset': (raw_data.get('meta') or {}).get('elite_tuning_preset'),
        'elite_diagnostics': _safe_get_nested(best_params, ['diagnostics', 'elite_diagnostics'], {}),
        'elite_fragility_index': _safe_get_nested(best_params, ['diagnostics', 'elite_diagnostics', 'fragility_index'], None),
        'elite_is_ridge': _safe_get_nested(best_params, ['diagnostics', 'elite_diagnostics', 'is_ridge_optimum'], False),
        'elite_basin_score': _safe_get_nested(best_params, ['diagnostics', 'elite_diagnostics', 'basin_score'], None),
        'elite_fragility_penalty': (best_params.get('elite_fragility_penalty') if best_params and isinstance(best_params, dict) else None) or 0.0,

        # Metadata
        'source': 'tuned_cache_bma',
        'timestamp': raw_data.get('timestamp') or raw_data.get('meta', {}).get('timestamp'),
        'model_posterior': model_posterior,
    }
    return result


def _select_regime_params(
    tuned_params: Dict,
    current_regime: int,
) -> Dict:
    """
    Select parameters using regime-first logic with global fallback.

    REGIME-FIRST PARAMETER ROUTING:

    1. If current_regime has tuned params AND not fallback → use regime params
    2. Otherwise → use global params

    This is parameter routing ONLY. No epistemology changes.

    Args:
        tuned_params: Full tuned params dict from _load_tuned_kalman_params()
        current_regime: Current regime index (0-4)

    Returns:
        Dict with selected params {q, phi, nu, c, fallback, regime_meta, ...}
    """
    if tuned_params is None:
        # No tuned params available - return minimal defaults
        return {
            'q': 1e-6,
            'phi': 0.95,
            'nu': None,
            'c': 1.0,
            'fallback': True,
            'source': 'defaults',
            'regime_used': None,
        }

    regime_data = tuned_params.get('regime') or {}
    global_data = tuned_params.get('global') or {}

    # Try to get regime-specific params
    # Handle both int keys and string keys (JSON converts to strings)
    regime_block = regime_data.get(current_regime) or regime_data.get(str(current_regime))

    # Helper to safely convert to float with fallback for None values
    def _safe_float(val, default):
        if val is None:
            return float(default)
        try:
            return float(val)
        except (TypeError, ValueError):
            return float(default)

    def _extract_best_model_params(model_posterior: Dict, models: Dict) -> Dict:
        """Extract params from highest-posterior model."""
        if not models:
            return {}

        # Helper to check if model is Student-t
        def _is_st(m: str) -> bool:
            return m.startswith('phi_student_t_nu_')

        if model_posterior:
            best_model = max(model_posterior.keys(), key=lambda m: model_posterior.get(m, 0))
        else:
            # Fallback order: any Student-t > phi_gaussian > gaussian
            student_t_models = [m for m in models if _is_st(m)]
            if student_t_models:
                best_model = student_t_models[0]
            elif 'kalman_phi_gaussian' in models:
                best_model = 'kalman_phi_gaussian'
            elif 'kalman_gaussian' in models:
                best_model = 'kalman_gaussian'
            else:
                best_model = next(iter(models), None)

        if best_model and best_model in models:
            return models[best_model]
        return {}

    # Check if regime has non-fallback data
    regime_meta = {}
    is_fallback = True
    if regime_block is not None and isinstance(regime_block, dict):
        regime_meta = regime_block.get('regime_meta', {})
        is_fallback = regime_meta.get('fallback', False) or regime_meta.get('borrowed_from_global', False)

    if regime_block is not None and not is_fallback:
        # Use regime-specific BMA params
        model_posterior = regime_block.get('model_posterior', {})
        models = regime_block.get('models', {})
        best_params = _extract_best_model_params(model_posterior, models)

        # Fallback to global if regime models empty
        if not best_params:
            global_model_posterior = global_data.get('model_posterior', {})
            global_models = global_data.get('models', {})
            best_params = _extract_best_model_params(global_model_posterior, global_models)

        theta = {
            'q': _safe_float(best_params.get('q'), 1e-6),
            'phi': _safe_float(best_params.get('phi'), 0.95) if best_params.get('phi') is not None else 0.95,
            'nu': best_params.get('nu'),
            'c': _safe_float(best_params.get('c'), 1.0),
            'fallback': False,
            'source': 'regime_bma',
            'regime_used': current_regime,
            'regime_name': regime_meta.get('regime_name', f'REGIME_{current_regime}'),
            'regime_meta': regime_meta,
            'collapse_warning': regime_meta.get('collapse_warning', False),
            'model_posterior': model_posterior,
            # Model selection diagnostics (best model)
            'hyvarinen_score': best_params.get('hyvarinen_score'),
            'combined_score': best_params.get('combined_score'),
            'bic': best_params.get('bic'),
            # Regime-level aggregates from regime_meta
            'hyvarinen_max': regime_meta.get('hyvarinen_max'),
            'combined_score_min': regime_meta.get('combined_score_min'),
            'bic_min': regime_meta.get('bic_min'),
            'model_selection_method': regime_meta.get('model_selection_method', 'combined'),
            'bic_weight': regime_meta.get('bic_weight', 0.5),
            'entropy_lambda': regime_meta.get('entropy_lambda', 0.05),
        }
        # Validate nu
        if theta['nu'] is not None and (not np.isfinite(theta['nu']) or theta['nu'] <= 2.0):
            theta['nu'] = None
        return theta
    else:
        # Fallback to global BMA params
        global_model_posterior = global_data.get('model_posterior', {})
        global_models = global_data.get('models', {})
        best_params = _extract_best_model_params(global_model_posterior, global_models)

        return {
            'q': _safe_float(best_params.get('q'), 1e-6),
            'phi': _safe_float(best_params.get('phi'), 0.95) if best_params.get('phi') is not None else 0.95,
            'nu': best_params.get('nu'),
            'c': _safe_float(best_params.get('c'), 1.0),
            'fallback': True,
            'source': 'global_bma',
            'regime_used': current_regime,
            'regime_name': 'GLOBAL_FALLBACK',
            'regime_meta': {},
            'collapse_warning': False,
            'model_posterior': global_model_posterior,
            # Model selection diagnostics (best model)
            'hyvarinen_score': best_params.get('hyvarinen_score'),
            'combined_score': best_params.get('combined_score'),
            'bic': best_params.get('bic'),
            # Global-level aggregates
            'hyvarinen_max': global_data.get('hyvarinen_max'),
            'combined_score_min': global_data.get('combined_score_min'),
            'bic_min': global_data.get('bic_min'),
            'model_selection_method': global_data.get('model_selection_method', 'combined'),
            'bic_weight': global_data.get('bic_weight', 0.5),
            'entropy_lambda': global_data.get('entropy_lambda', 0.05),
        }

